WEATHER_CODES = {
    0:  ("Clear sky", "☀️"),
    1:  ("Mainly clear", "🌤️"),
    2:  ("Partly cloudy", "⛅"),
    3:  ("Overcast", "☁️"),
    45: ("Fog", "🌫️"),
    48: ("Depositing rime fog", "🌫️"),
    51: ("Light drizzle", "🌦️"),
    53: ("Moderate drizzle", "🌦️"),
    55: ("Dense drizzle", "🌧️"),
    56: ("Light freezing drizzle", "🌧️❄️"),
    57: ("Freezing drizzle", "🌧️❄️"),
    61: ("Slight rain", "🌧️"),
    63: ("Rain", "🌧️"),
    65: ("Heavy rain", "🌧️🌧️"),
    66: ("Light freezing rain", "🌧️❄️"),
    67: ("Freezing rain", "🌧️❄️"),
    71: ("Slight snow fall", "❄️"),
    73: ("Snow fall", "❄️"),
    75: ("Heavy snow fall", "❄️❄️"),
    77: ("Snow grains", "❄️"),
    80: ("Rain showers", "🌧️🌧️"),
    81: ("Moderate rain showers", "🌧️"),
    82: ("Violent rain showers", "🌧️🌧️🌧️"),
    85: ("Snow showers", "🌨️"),
    86: ("Heavy snow showers", "🌨️❄️"),
    95: ("Thunderstorm", "⛈️"),
    96: ("Thunderstorm with slight hail", "⛈️❄️"),
    99: ("Thunderstorm with heavy hail", "⛈️❄️"),
}

def interpret_weather_code(code: int) -> tuple[str, str]:
    return WEATHER_CODES.get(code, ("Unknown",  "❓"))
